### PR TITLE
Added resolveURL param

### PR DESCRIPTION
**Pull request by Daemach**
I needed to set the resolveURL parameter for hyper.

### CODE REVIEW

**Comment by elpete** [comment]
I am so curious, what does this do? I have read the docs for CFHTTP and can’t picture it yet. Can you show an example?

**Comment by Daemach** [comment]
It converts /relativeURL to http://thedomain.com/nowabsoluteURL

**Comment by Daemach** [comment]
I needed it as a proxy to make creating a bill of materials on digikey.com easier.  It's tedious at the moment.  All of their images are loaded with relative URLs which is fine if you're hitting their site directly.  But in a proxied frame I need all of the URLS (stylesheets, JS, images, links to other pages) to include the base URL.  resolveURL does this automatically.

**Comment by elpete** [comment]
Published as [v2.2.0](https://github.com/coldbox-modules/hyper/releases/tag/v2.2.0)

**Pull request merged**
