### PR TITLE
Do not include username & password in cfhttp unless they have values

### PR DESCRIPTION
**Pull request by MordantWastrel**

### CODE REVIEW

**Comment by elpete** [comment]
Looks like it needs some Lucee 4 love.

**Comment by MordantWastrel** [comment]
I'm not sure I understand the error:

`attribute url is required for statement http` (on the cfhttp call)

But the attributecollection has url in it.

I'm not familiar with Lucee 4.5 quirks though.

**Comment by elpete** [comment]
My guess is Lucee 4.5 isn't playing nice with `attributeCollection`. ☹️

**Comment by elpete** [comment]
Let's drop Lucee 4.5.  I made the change already.  Thanks for the PR!

**Pull request merged**
